### PR TITLE
Enhancing generic unlock check

### PR DESCRIPTION
**Pull request by modhunter**
Currently if you're using a generic unlock, the following is necessary for the engine to know that it's unlocked:

1. Execute unlocker outside of WOW process
2. Click on 'Unlock!' in the NeP dropdown menu
3. Toggle on the NeP master toggle if it isn't already

In other words, there isn't an automatic way for the engine to detect a generic unlock unless the user clicks on the button or unlocks before entering the world.

This patch adds `/run NeP.Protected.Generic_Check = true` as a fallthrough check inside the timer so that the engine will automatically detect when it's unlocked.

### CODE REVIEW

**Comment by modhunter** [comment]
Ok I think the check needs to be tied to the engine being turned on. Please don't merge this yet if you were thinking about it.

**Comment by MrTheSoulz** [comment]
I havent done this because someone complained about it making "clicking noises".
Im also not sure how safe it is to make alot of pcalls...

**Comment by MrTheSoulz** [comment]
Pcalls should be safe, i think...
http://wowprogramming.com/docs/api/pcall

Instead of running the macro you could try running a protected api and then do if pcall...

Should stop the clicking noises

**Comment by modhunter** [comment]
ok this is a good suggestion, I'll look into this.

**Comment by modhunter** [comment]
@MrTheSoulz I've been looking through the protected API and can't find an benign candidate to call as a sanity-check instead of the `/run` macro:  http://wowwiki.wikia.com/wiki/Category:World_of_Warcraft_API/Protected_Functions

Everything seems to take some invasive action.  Do you think it's ok to only attempt the check if the engine is 'enabled'?  If so, that was added to this PR as part of https://github.com/MrTheSoulz/NerdPack-Protected/pull/2/commits/bac80005a974785d4504dcaa7a392ce364659c7c

**Pull request closed without merging**
